version: "3.8"
services:
  api:
    container_name: sn_api
    build:
      context: .
      target: prod
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./migrations/versions/:/app/migrations/versions/

  db:
    container_name: sn_db
    image: "postgres:13-alpine"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_DB}"
    ports:
      - 5432:5432
volumes:
  postgres-data: null